package model;
// Generated May 4, 2019 8:01:01 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "Account", schema = "dbo", catalog = "Badminton")
public class Account implements java.io.Serializable {

	private Integer id;
	private Serializable username;
	private Serializable password;
	private Serializable fullname;
	private Date birthday;
	private Serializable sex;
	private Serializable phoneNumber;
	private Serializable email;
	private Serializable address;
	private Serializable permission;
	private Serializable active;
	private Set<Bill> bills = new HashSet<Bill>(0);

	public Account() {
	}

	public Account(Serializable username, Serializable password, Serializable fullname, Date birthday) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.birthday = birthday;
	}

	public Account(Serializable username, Serializable password, Serializable fullname, Date birthday, Serializable sex,
			Serializable phoneNumber, Serializable email, Serializable address, Serializable permission,
			Serializable active, Set<Bill> bills) {
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.birthday = birthday;
		this.sex = sex;
		this.phoneNumber = phoneNumber;
		this.email = email;
		this.address = address;
		this.permission = permission;
		this.active = active;
		this.bills = bills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Username", nullable = false)
	public Serializable getUsername() {
		return this.username;
	}

	public void setUsername(Serializable username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false)
	public Serializable getPassword() {
		return this.password;
	}

	public void setPassword(Serializable password) {
		this.password = password;
	}

	@Column(name = "Fullname", nullable = false)
	public Serializable getFullname() {
		return this.fullname;
	}

	public void setFullname(Serializable fullname) {
		this.fullname = fullname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Birthday", nullable = false, length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Sex")
	public Serializable getSex() {
		return this.sex;
	}

	public void setSex(Serializable sex) {
		this.sex = sex;
	}

	@Column(name = "PhoneNumber")
	public Serializable getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Serializable phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "Address")
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "Permission")
	public Serializable getPermission() {
		return this.permission;
	}

	public void setPermission(Serializable permission) {
		this.permission = permission;
	}

	@Column(name = "Active")
	public Serializable getActive() {
		return this.active;
	}

	public void setActive(Serializable active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Bill> getBills() {
		return this.bills;
	}

	public void setBills(Set<Bill> bills) {
		this.bills = bills;
	}

}
