package model;
// Generated May 4, 2019 8:01:01 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bill generated by hbm2java
 */
@Entity
@Table(name = "Bill", schema = "dbo", catalog = "Badminton")
public class Bill implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Date date;
	private Serializable fullname;
	private Serializable phonenumber;
	private Serializable address;
	private Serializable email;
	private Serializable totalPrice;
	private Serializable status;
	private Set<BillDetails> billDetailses = new HashSet<BillDetails>(0);

	public Bill() {
	}

	public Bill(Account account, Date date, Serializable fullname, Serializable phonenumber, Serializable address,
			Serializable totalPrice, Serializable status) {
		this.account = account;
		this.date = date;
		this.fullname = fullname;
		this.phonenumber = phonenumber;
		this.address = address;
		this.totalPrice = totalPrice;
		this.status = status;
	}

	public Bill(Account account, Date date, Serializable fullname, Serializable phonenumber, Serializable address,
			Serializable email, Serializable totalPrice, Serializable status, Set<BillDetails> billDetailses) {
		this.account = account;
		this.date = date;
		this.fullname = fullname;
		this.phonenumber = phonenumber;
		this.address = address;
		this.email = email;
		this.totalPrice = totalPrice;
		this.status = status;
		this.billDetailses = billDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AccountID", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "Fullname", nullable = false)
	public Serializable getFullname() {
		return this.fullname;
	}

	public void setFullname(Serializable fullname) {
		this.fullname = fullname;
	}

	@Column(name = "Phonenumber", nullable = false)
	public Serializable getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(Serializable phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "Address", nullable = false)
	public Serializable getAddress() {
		return this.address;
	}

	public void setAddress(Serializable address) {
		this.address = address;
	}

	@Column(name = "Email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "TotalPrice", nullable = false)
	public Serializable getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(Serializable totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "Status", nullable = false)
	public Serializable getStatus() {
		return this.status;
	}

	public void setStatus(Serializable status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bill")
	public Set<BillDetails> getBillDetailses() {
		return this.billDetailses;
	}

	public void setBillDetailses(Set<BillDetails> billDetailses) {
		this.billDetailses = billDetailses;
	}

}
