package model;
// Generated May 4, 2019 8:01:01 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BillDetails generated by hbm2java
 */
@Entity
@Table(name = "Bill_Details", schema = "dbo", catalog = "Badminton")
public class BillDetails implements java.io.Serializable {

	private BillDetailsId id;
	private Bill bill;
	private Product product;
	private int amount;
	private int price;

	public BillDetails() {
	}

	public BillDetails(BillDetailsId id, Bill bill, Product product, int amount, int price) {
		this.id = id;
		this.bill = bill;
		this.product = product;
		this.amount = amount;
		this.price = price;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "ProductID", nullable = false)),
			@AttributeOverride(name = "billId", column = @Column(name = "BillID", nullable = false)) })
	public BillDetailsId getId() {
		return this.id;
	}

	public void setId(BillDetailsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BillID", nullable = false, insertable = false, updatable = false)
	public Bill getBill() {
		return this.bill;
	}

	public void setBill(Bill bill) {
		this.bill = bill;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductID", nullable = false, insertable = false, updatable = false)
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Column(name = "Amount", nullable = false)
	public int getAmount() {
		return this.amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}

	@Column(name = "Price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

}
