package model;
// Generated May 4, 2019 8:01:01 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "News", schema = "dbo", catalog = "Badminton")
public class News implements java.io.Serializable {

	private Integer id;
	private NewsType newsType;
	private Serializable title;
	private int isPublic;
	private Serializable content;
	private Serializable author;
	private Date createdDate;

	public News() {
	}

	public News(NewsType newsType, Serializable title, int isPublic, Serializable content, Date createdDate) {
		this.newsType = newsType;
		this.title = title;
		this.isPublic = isPublic;
		this.content = content;
		this.createdDate = createdDate;
	}

	public News(NewsType newsType, Serializable title, int isPublic, Serializable content, Serializable author,
			Date createdDate) {
		this.newsType = newsType;
		this.title = title;
		this.isPublic = isPublic;
		this.content = content;
		this.author = author;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NewsTypeID", nullable = false)
	public NewsType getNewsType() {
		return this.newsType;
	}

	public void setNewsType(NewsType newsType) {
		this.newsType = newsType;
	}

	@Column(name = "Title", nullable = false)
	public Serializable getTitle() {
		return this.title;
	}

	public void setTitle(Serializable title) {
		this.title = title;
	}

	@Column(name = "IsPublic", nullable = false)
	public int getIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(int isPublic) {
		this.isPublic = isPublic;
	}

	@Column(name = "Content", nullable = false)
	public Serializable getContent() {
		return this.content;
	}

	public void setContent(Serializable content) {
		this.content = content;
	}

	@Column(name = "Author")
	public Serializable getAuthor() {
		return this.author;
	}

	public void setAuthor(Serializable author) {
		this.author = author;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CreatedDate", nullable = false, length = 10)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
