package model;
// Generated May 4, 2019 8:01:01 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producer generated by hbm2java
 */
@Entity
@Table(name = "Producer", schema = "dbo", catalog = "Badminton")
public class Producer implements java.io.Serializable {

	private Integer id;
	private String name;
	private String images;
	private Set<Product> products = new HashSet<Product>(0);

	public Producer() {
	}

	public Producer(String name, String images) {
		this.name = name;
		this.images = images;
	}

	public Producer(String name, String images, Set<Product> products) {
		this.name = name;
		this.images = images;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Images", nullable = false)
	public String getImages() {
		return this.images;
	}

	public void setImages(String images) {
		this.images = images;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producer")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
